name: Feature request
description: Propose an enhancement
title: "Feature: "
labels:
  - feature
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: Constraints / tradeoffs